name: argumentative_language
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.5.0
  - argon2-cffi=20.1.0
  - arviz=0.11.4
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - binutils_impl_linux-64=2.35.1
  - binutils_linux-64=2.35.1
  - bleach=4.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.26
  - cachetools=5.0.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - cftime=1.5.1.1
  - charset-normalizer=2.0.11
  - cryptography=35.0.0
  - curl=7.80.0
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.4
  - entrypoints=0.4
  - fastprogress=1.0.0
  - filelock=3.4.2
  - freetype=2.10.4
  - gcc_impl_linux-64=9.3.0
  - gcc_linux-64=9.3.0
  - gxx_impl_linux-64=9.3.0
  - gxx_linux-64=9.3.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=67.1
  - idna=3.3
  - importlib-metadata=4.10.1
  - importlib_metadata=4.10.1
  - importlib_resources=5.4.0
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=4.4.0
  - jupyter_client=7.1.2
  - jupyter_core=4.9.1
  - jupyter_server=1.13.4
  - jupyterlab=3.2.9
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.80.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-devel_linux-64=9.3.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-devel_linux-64=9.3.0
  - libstdcxx-ng=9.3.0
  - libuuid=1.0.3
  - libzip=1.8.0
  - markupsafe=2.0.1
  - matplotlib-base=3.2.2
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - nbclassic=0.3.5
  - nbclient=0.5.10
  - nbconvert=6.4.1
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - netcdf4=1.5.7
  - notebook=6.4.8
  - numpy=1.20.3
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.2.3
  - pandoc=2.17.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.0.3
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.26
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.11.2
  - pymc3=3.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.3
  - pyzmq=19.0.2
  - readline=8.1.2
  - requests=2.27.1
  - scipy=1.5.3
  - semver=2.13.0
  - send2trash=1.8.0
  - setuptools=59.8.0
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.37.0
  - sysroot_linux-64=2.12
  - terminado=0.13.1
  - testpath=0.5.0
  - theano-pymc=1.1.2
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.2.3
  - wheel=0.37.1
  - xarray=0.21.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
prefix: /home/fausto/anaconda3/envs/argumentative_language
