name: /home/fausto/anaconda3/envs/argumentative_language
channels:
  - anaconda
  - plotly
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=1.3.0=py38h06a4308_0
  - alsa-lib=1.2.8=h166bdaf_0
  - anyio=3.5.0=py38h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - arviz=0.14.0=pyhd8ed1ab_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - attr=2.5.1=h166bdaf_1
  - attrs=22.1.0=py38h06a4308_0
  - babel=2.11.0=py38h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38h06a4308_0
  - binutils=2.43=h4852527_4
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - binutils_linux-64=2.43=h4852527_4
  - blackjax=0.9.6=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.34.5=hb9d3cd8_0
  - c-compiler=1.9.0=h2b85faf_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.0=pyhd8ed1ab_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.1=py38h5eee18b_3
  - cftime=1.6.2=py38h26c90d9_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cryptography=39.0.1=py38h9ce1e76_0
  - cuda=12.0.0=0
  - cuda-cccl=12.0.90=0
  - cuda-command-line-tools=12.0.0=0
  - cuda-compiler=12.0.0=0
  - cuda-cudart=12.0.107=0
  - cuda-cudart-dev=12.0.107=0
  - cuda-cudart-static=12.0.107=0
  - cuda-cuobjdump=12.0.76=0
  - cuda-cupti=12.0.90=0
  - cuda-cupti-static=12.0.90=0
  - cuda-cuxxfilt=12.0.76=0
  - cuda-demo-suite=12.0.76=0
  - cuda-documentation=12.0.76=0
  - cuda-driver-dev=12.0.107=0
  - cuda-gdb=12.0.90=0
  - cuda-libraries=12.0.0=0
  - cuda-libraries-dev=12.0.0=0
  - cuda-libraries-static=12.0.0=0
  - cuda-nsight=12.0.78=0
  - cuda-nsight-compute=12.0.0=0
  - cuda-nvcc=12.0.76=0
  - cuda-nvdisasm=12.0.76=0
  - cuda-nvml-dev=12.0.76=0
  - cuda-nvprof=12.0.90=0
  - cuda-nvprune=12.0.76=0
  - cuda-nvrtc=12.0.76=0
  - cuda-nvrtc-dev=12.0.76=0
  - cuda-nvrtc-static=12.0.76=0
  - cuda-nvtx=12.0.76=0
  - cuda-nvvp=12.0.90=0
  - cuda-opencl=12.0.76=0
  - cuda-opencl-dev=12.0.76=0
  - cuda-profiler-api=12.0.76=0
  - cuda-runtime=12.0.0=0
  - cuda-sanitizer-api=12.0.90=0
  - cuda-toolkit=12.0.0=0
  - cuda-tools=12.0.0=0
  - cuda-visual-tools=12.0.0=0
  - curl=8.1.2=h409715c_0
  - cxx-compiler=1.9.0=h1a2810e_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecat=2.1.3=pyhd8ed1ab_0
  - dill=0.3.9=pyhd8ed1ab_0
  - entrypoints=0.4=py38h06a4308_0
  - expat=2.7.0=h5888daf_0
  - fastprogress=1.0.0=pyhb85f177_0
  - fftw=3.3.10=nompi_hf0379b8_106
  - filelock=3.9.0=py38h06a4308_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gcc=13.3.0=h9576a4e_2
  - gcc_impl_linux-64=13.3.0=h1e990d8_2
  - gcc_linux-64=13.3.0=hc28eda2_10
  - gdk-pixbuf=2.42.8=h5eee18b_2
  - gds-tools=1.5.0.59=0
  - gettext=0.23.1=h5888daf_0
  - gettext-tools=0.23.1=h5888daf_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - gobject-introspection=1.72.0=py38hbb6d50b_1
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h3cd0ef9_0
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.41=h17648ed_0
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - gxx=13.3.0=h9576a4e_2
  - gxx_impl_linux-64=13.3.0=hae580e1_2
  - gxx_linux-64=13.3.0=h6834431_10
  - h5netcdf=1.0.0=pyhd8ed1ab_0
  - h5py=3.7.0=nompi_py38h8afedcf_100
  - harfbuzz=4.4.1=hf9f4e7c_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.1=nompi_h4df4325_104
  - icu=70.1=h27087fc_0
  - idna=3.4=py38h06a4308_0
  - importlib-metadata=4.11.3=py38h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.4.1=py38h06a4308_1
  - ipython=7.31.1=py38h06a4308_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.7.1=pyhd8ed1ab_0
  - jack=1.9.22=h11f4161_0
  - jax=0.3.25=py38h06a4308_0
  - jaxopt=0.5.5=pyhd8ed1ab_0
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.1.2=py38h06a4308_0
  - joblib=1.1.1=py38h06a4308_0
  - jpeg=9e=h7f8727e_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py38h06a4308_0
  - jupyter_client=7.4.9=py38h06a4308_0
  - jupyter_core=5.2.0=py38h06a4308_0
  - jupyter_server=1.23.4=py38h06a4308_0
  - jupyterlab=3.2.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.19.0=py38h06a4308_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=3.0=h295c915_0
  - libasprintf=0.23.1=h8e693c7_0
  - libasprintf-devel=0.23.1=h8e693c7_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcublas=12.0.1.189=0
  - libcublas-dev=12.0.1.189=0
  - libcublas-static=12.0.1.189=0
  - libcufft=11.0.0.21=0
  - libcufft-dev=11.0.0.21=0
  - libcufft-static=11.0.0.21=0
  - libcufile=1.5.0.59=0
  - libcufile-dev=1.5.0.59=0
  - libcufile-static=1.5.0.59=0
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.3.1.50=0
  - libcurand-dev=10.3.1.50=0
  - libcurand-static=10.3.1.50=0
  - libcurl=8.1.2=h409715c_0
  - libcusolver=11.4.2.57=0
  - libcusolver-dev=11.4.2.57=0
  - libcusolver-static=11.4.2.57=0
  - libcusparse=12.0.0.76=0
  - libcusparse-dev=12.0.0.76=0
  - libcusparse-static=12.0.0.76=0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h28343ad_4
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.2=h6a678d5_6
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=13.3.0=hc03c837_102
  - libgcc-ng=14.2.0=h69a702a_2
  - libgcrypt=1.11.0=ha770c72_2
  - libgcrypt-devel=1.11.0=hb9d3cd8_2
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgcrypt-tools=1.11.0=hb9d3cd8_2
  - libgd=2.3.3=h5aea950_4
  - libgettextpo=0.23.1=h5888daf_0
  - libgettextpo-devel=0.23.1=h5888daf_0
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.80.2=hf974151_0
  - libgomp=14.2.0=h767d61c_2
  - libgpg-error=1.55=h3f2d84a_0
  - libiconv=1.18=h4ce23a2_1
  - liblapack=3.9.0=12_linux64_mkl
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm11=11.1.0=h9e868ea_6
  - libllvm15=15.0.7=hadd5161_1
  - libnetcdf=4.8.1=nompi_h329d8a1_102
  - libnghttp2=1.58.0=h47da74e_0
  - libnpp=12.0.0.30=0
  - libnpp-dev=12.0.0.30=0
  - libnpp-static=12.0.0.30=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.0.76=0
  - libnvjitlink-dev=12.0.76=0
  - libnvjpeg=12.0.0.28=0
  - libnvjpeg-dev=12.0.0.28=0
  - libnvjpeg-static=12.0.0.28=0
  - libnvvm-samples=12.0.94=0
  - libogg=1.3.5=hd0c01bc_1
  - libopus=1.5.2=hd0c01bc_0
  - libpng=1.6.43=h2797004_0
  - libpq=15.3=hbcd7760_1
  - librsvg=2.54.4=h7abd40a_0
  - libsanitizer=13.3.0=he8ea267_2
  - libsndfile=1.1.0=hcb278e6_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=13.3.0=hc03c837_102
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsystemd0=252=h2a991cd_0
  - libtiff=4.5.0=h6a678d5_2
  - libtool=2.4.6=h6a678d5_1009
  - libudev1=253=h0b41bf4_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libxslt=1.1.37=h873f0b0_0
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=h4ab18f5_6
  - llvmlite=0.39.1=py38he621ea3_0
  - lxml=4.9.2=py38h215a2d7_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib=3.7.0=py38h06a4308_0
  - matplotlib-base=3.7.0=py38h417a72b_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h497a2fe_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mpg123=1.31.3=hcb278e6_0
  - munkres=1.1.4=py_0
  - mysql-common=8.0.33=hf1915f5_2
  - mysql-libs=8.0.33=hca2cd23_2
  - nbclassic=0.5.2=py38h06a4308_0
  - nbclient=0.5.13=py38h06a4308_0
  - nbconvert=6.5.4=py38h06a4308_0
  - nbformat=5.7.0=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py38h06a4308_0
  - netcdf4=1.6.0=nompi_py38he1ab104_100
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - notebook=6.5.2=py38h06a4308_0
  - notebook-shim=0.2.2=py38h06a4308_0
  - nsight-compute=2022.4.0.15=0
  - nspr=4.36=h5888daf_0
  - nss=3.100=hca3bf56_0
  - numba=0.56.4=py38h417a72b_0
  - numexpr=2.8.4=py38he184ba9_0
  - numpy=1.21.5=py38h6c91a56_3
  - numpy-base=1.21.5=py38ha15fc14_3
  - openssl=3.1.8=h7b32b05_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=22.0=py38h06a4308_0
  - pandas=1.5.2=py38h417a72b_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.7=h05da053_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=0.5.3=py38h06a4308_0
  - pcre=8.45=h295c915_0
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py38h6a678d5_0
  - pip=22.3.1=py38h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pkgutil-resolve-name=1.3.10=py38h06a4308_0
  - platformdirs=2.5.2=py38h06a4308_0
  - plotly=5.7.0=py_0
  - ply=3.11=py38_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - prometheus_client=0.14.1=py38h06a4308_0
  - prompt-toolkit=3.0.36=py38h06a4308_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio=16.1=h126f2b6_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydot=1.4.1=py38h06a4308_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pymc3=3.11.4=py38h83c9d95_1
  - pyopenssl=23.0.0=py38h06a4308_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.15.7=py38h7492b6b_0
  - pyqt5-sip=12.11.0=py38hfa26641_0
  - pyrsistent=0.18.0=py38heee7806_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.12=h0744224_3_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py38h06a4308_0
  - python-graphviz=0.19.1=pyhaef67bd_0
  - python-ternary=1.0.8=pyhd8ed1ab_1
  - python_abi=3.8=2_cp38
  - pytz=2022.7=py38h06a4308_0
  - pyzmq=23.2.0=py38h6a678d5_0
  - qt-main=5.15.6=hf6cd601_5
  - qt-webengine=5.15.4=h325cec9_3
  - qtwebkit=5.212=h3e5094c_7
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py38h06a4308_0
  - scikit-learn=1.1.1=py38h6a678d5_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - semver=3.0.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py38h06a4308_0
  - sip=6.6.2=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py38h06a4308_1
  - soupsieve=2.3.2.post1=py38h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - statsmodels=0.13.5=py38h7deecbd_1
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2021.7.0=hdb19cb5_0
  - tenacity=8.0.1=py38h06a4308_1
  - terminado=0.17.1=py38h06a4308_0
  - theano-pymc=1.1.2=py38h51133e4_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.2.1=py38h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.2=py38h5eee18b_0
  - traitlets=5.7.1=py38h06a4308_0
  - typing-extensions=4.4.0=py38h06a4308_0
  - typing_extensions=4.4.0=py38h06a4308_0
  - tzdata=2025b=h78e105d_0
  - urllib3=1.26.14=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=0.58.0=py38h06a4308_4
  - wheel=0.38.4=py38h06a4308_0
  - widgetsnbextension=3.6.1=pyha770c72_0
  - wrapt=1.16.0=py38h01eb140_0
  - xarray=2023.1.0=pyhd8ed1ab_0
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.2.10=h5eee18b_1
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py38h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - aeppl==0.0.38
      - aesara==2.8.7
      - bambi==0.9.1
      - cloudpickle==2.2.0
      - cons==0.4.5
      - etuples==0.3.8
      - formulae==0.3.4
      - jaxlib==0.3.22+cuda11.cudnn82
      - line-profiler==4.0.2
      - logical-unification==0.4.5
      - minikanren==1.0.3
      - multipledispatch==0.6.0
      - numpyro==0.10.1
      - progress==1.6
      - pymc==4.2.2
      - scipy==1.9.2
      - simanneal==0.5.0
      - toolz==0.12.0
      - tqdm==4.64.1
      - xarray-einstats==0.3.0
prefix: /home/fausto/anaconda3/envs/argumentative_language
